CREATE TABLE strona(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nazwa VARCHAR(255) NOT NULL UNIQUE,
    id_tworcy INT NOT NULL
);

CREATE TABLE uzytkownicy(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    imie VARCHAR(255) NOT NULL,
    nazwisko VARCHAR(255) NOT NULL
);
